### ISSUE TITLE
Problem  Running on AWS Lambda

### ISSUE THREAD

**Issue by vectorhacker** [Unleash/unleash-proxy#98] opened 2022-09-16 15:18 UTC
### Describe the bug

I'm getting an error when running unleash proxy behind a lambda function of it not being able to use a functions utils.forOwn. I'm running the proxy behind a lambda function using the `serverless-http` package.

### Steps to reproduce the bug

1. Setup an http lambda function 
2. Write this code
```typescript
import unleash from '@unleash/proxy';
import { LogLevel } from '@unleash/proxy/dist/logger';
import { APIGatewayProxyHandlerV2 } from 'aws-lambda';
import serverless from 'serverless-http';

const app = unleash.createApp({
  unleashUrl: process.env.UNLEASH_URL,
  unleashInstanceId: process.env.UNLEASH_INSTANCE_ID,
  unleashAppName: process.env.UNLEASH_APP_NAME,
  clientKeys: [process.env.UNLEASH_PROXY_CLIENT_KEYS!],
  unleashApiToken: process.env.UNLEASH_API_TOKEN,
  refreshInterval: 1000,
  logLevel: LogLevel.debug,
  enableOAS: true,
  proxyBasePath: '/unleash',
});

export const handler: APIGatewayProxyHandlerV2 = serverless(app);
```
3. Make any /unleash/proxy call

### Expected behavior

A list of toggles

```json
{
  "toggles": [
    {
      "name": "string",
      "enabled": true,
      "impressionData": true,
      "variant": {
        "name": "string",
        "enabled": true,
        "payload": {
          "type": "string",
          "value": "string"
        }
      }
    }
  ]
```

### Logs, error output, etc.

```bash
{"error":"Whoops! We dropped the ball on this one (an unexpected error occurred): utils.forOwn is not a function"}
```

### Additional context

I'm utilizing the sst framework, hosting the endpoint behind a /unleash/{proxy+} endpoint through an AWS Api Gateway HTTP API 

### Unleash version

0.10.4

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by vectorhacker** [comment] 2022-09-16 16:15
I'm able only to view the open API ui

**Comment by sighphyre** [comment] 2022-09-23 09:01
Hey @vectorhacker I'm not sure what's causing this off the top of my head but I'll add it to our triage for next week

**Comment by vectorhacker** [comment] 2022-09-26 15:40
@sighphyre thanks for letting me know!

**Comment by vectorhacker** [comment] 2022-10-01 17:05
@sighphyre any update on this?

**Comment by sighphyre** [comment] 2022-10-02 10:40
Hey @vectorhacker, not at the moment, I'm actually on leave at the moment but I've asked a team mate to look into this one tomorrow. Otherwise I'll pick it up on Wednesday

**Comment by gastonfournier** [comment] 2022-10-03 08:48
Hi @vectorhacker one quick question about _Setup an http lambda function_. How are you setting it up? Manually from AWS console or through a serverless?

If it's the latter, maybe you can share the serverless config (after removing the environment values that have your secrets). That'd help me to reproduce this.

**Comment by gastonfournier** [comment] 2022-10-04 09:55
Hi @vectorhacker, I managed to run the proxy using the following code and the config from https://github.com/Unleash/unleash-proxy:
[sls-lambda-test.zip](https://github.com/Unleash/unleash-proxy/files/9704696/sls-lambda-test.zip)

1. Unzip
2. Run `yarn` to download package dependencies
3. Run `serverless deploy`
4. Test `curl -H 'Authorization: proxy-secret' -H 'Accept: application/json' <endpoint>/unleash/proxy` (note it may take some attempts until the proxy connects with Unleash server)

It seems your setup is slightly different and you might be using Typescript, so let me know if this helps you

**Comment by vectorhacker** [comment] 2022-10-14 18:13
> Hi @vectorhacker one quick question about _Setup an http lambda function_. How are you setting it up? Manually from AWS console or through a serverless?
> 
> If it's the latter, maybe you can share the serverless config (after removing the environment values that have your secrets). That'd help me to reproduce this.

We're using a serverless framework to deploy it along side our app. We use sst.

**Comment by vectorhacker** [comment] 2022-10-14 18:14
> Hi @vectorhacker, I managed to run the proxy using the following code and the config from https://github.com/Unleash/unleash-proxy: [sls-lambda-test.zip](https://github.com/Unleash/unleash-proxy/files/9704696/sls-lambda-test.zip)
> 
> 1. Unzip
> 2. Run `yarn` to download package dependencies
> 3. Run `serverless deploy`
> 4. Test `curl -H 'Authorization: proxy-secret' -H 'Accept: application/json' <endpoint>/unleash/proxy` (note it may take some attempts until the proxy connects with Unleash server)
> 
> It seems your setup is slightly different and you might be using Typescript, so let me know if this helps you

I'll set it up similarly, we use typescript.

**Comment by vectorhacker** [comment] 2022-10-14 18:25
Is there a reason why you pinned `serverless-http` to version `2.7.0`?

**Comment by vectorhacker** [comment] 2022-10-14 18:48
The same problem, getting `{"error":"Whoops! We dropped the ball on this one (an unexpected error occurred): utils.forOwn is not a function"}`

**Comment by vectorhacker** [comment] 2022-10-14 18:49
This is our proxy stack

```ts
import { StackContext, use } from '@serverless-stack/resources';
import { ApiStack } from './Api';

export function UnleahProxyStack({ stack }: StackContext) {
  const { api } = use(ApiStack);

  api.addRoutes(stack, {
    'ANY /unleash/{proxy+}': {
      authorizer: 'none',
      function: 'unleash-proxy/proxy.handler',
    },
  });
}
```

This is the function handler
```
import { createApp } from '@unleash/proxy';
import { LogLevel } from '@unleash/proxy/dist/logger';
import serverless from 'serverless-http';

const unleashApp = createApp({
  unleashUrl: 'https://app.unleash-hosted.com/demo/api/',
  unleashApiToken: '56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d',
  clientKeys: ['proxy-secret'],
  logLevel: LogLevel.debug,
  unleashAppName: 'default',
  environment: 'development',
  proxyBasePath: '/unleash',
});

export const handler = serverless(unleashApp);
```

**Comment by gastonfournier** [comment] 2022-10-17 17:26
> Is there a reason why you pinned `serverless-http` to version `2.7.0`?

No particular reason, probably it was there from the example I used to have it up and running. I tested with `3.0.3` but this was not the problem

I set myself to testing with SST, and I managed to reproduce the bug, but the bad news is I have no idea yet what's causing this. I'll have to involve the team to see what's going on.

The "good" news is that the issue starts with `0.10.0` of the proxy, so as a workaround you should be able to use `0.8.1` until we resolve the issue. Please, if you do test with that version of the proxy, do let us know the result.

**Comment by vectorhacker** [comment] 2022-10-20 16:00
I'll try it out!

**Comment by ivarconr** [comment] 2023-01-24 18:59
Closing due to inativity.

**Closed by ivarconr** 2023-01-24 18:59 UTC
Labels: bug
